version: "3.8"

services:
  db:
    image: postgres:16
    container_name: go-boilerplate-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - go-boilerplate-db:/var/lib/postgresql/data

volumes:
  go-boilerplate-db: