version: "3.8"

services:
  db:
    image: postgres:16
    container_name: go-boilerplate-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - go-boilerplate-db:/var/lib/postgresql/data
  app:
    image: go-boilerplate
    container_name: go-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  go-boilerplate-db: